//<auto-generated />
namespace AvroFunctions
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record AvroFunctions.DataRecord.
    /// </summary>
    [DataContract(Namespace = "AvroFunctions")]
    public partial class DataRecord
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""AvroFunctions.DataRecord"",""fields"":[{""name"":""one"",""type"":""int""},{""name"":""two"",""type"":""int""},{""name"":""id"",""type"":{""type"":""record"",""name"":""AvroFunctions.RecordId"",""fields"":[{""name"":""id_num"",""type"":""int""},{""name"":""id_str"",""type"":""string""}]}},{""name"":""three"",""type"":""string""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the one field.
        /// </summary>
        [DataMember]
        public int one { get; set; }
              
        /// <summary>
        /// Gets or sets the two field.
        /// </summary>
        [DataMember]
        public int two { get; set; }
              
        /// <summary>
        /// Gets or sets the id field.
        /// </summary>
        [DataMember]
        public AvroFunctions.RecordId id { get; set; }
              
        /// <summary>
        /// Gets or sets the three field.
        /// </summary>
        [DataMember]
        public string three { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="DataRecord"/> class.
        /// </summary>
        public DataRecord()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataRecord"/> class.
        /// </summary>
        /// <param name="one">The one.</param>
        /// <param name="two">The two.</param>
        /// <param name="id">The id.</param>
        /// <param name="three">The three.</param>
        public DataRecord(int one, int two, AvroFunctions.RecordId id, string three)
        {
            this.one = one;
            this.two = two;
            this.id = id;
            this.three = three;
        }
    }
}
